import { defaultTheme } from '@/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeProvider theme={defaultTheme}>
				<body>
					<CssBaseline />
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
